name = "Cute Cars"
author = "CuteCarsMC"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c020cfd8b8baeb9a16fd2be6bd583c871e4f30e1c0dbba40044dc763d88b641"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
