name = "Cute Cars"
author = "CuteCarsMC"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a632b17f87f1cb24f3905d2692076344a15dab946907a56c1f9fb79e9d5a867"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
